### PR TITLE
add linux and macOS ci

### PR DESCRIPTION
**Pull request by ghost**
Currently only Linux uploads artifacts as an AppImage, and macOS is solely for building. Keep in mind that I did not test if the generated AppImage actually works. It would be appreciated if you could test it, or I'll have to create a Linux VM and check if it works on another day.

### CODE REVIEW

**Comment by ghost** [comment]
Okay, I've tested this in a VM, and it appears that gstreamer 1.0 would also need to be bundled in the AppImage, but unfortunately that seems not very viable from what I've read online because the rpath seems to be different on many distros and even different Ubuntu versions.

Not sure where to go from here, but it seems like the easiest way for Linux users is probably to build from source.

**Comment by ghost** [comment]
PR should be good to go now, no Linux artifacts though :/

**Comment by memmaa** [comment]
Thanks very much.
As building from source was already the best way to get it running on
Linux, I suppose we're no worse off than we were before!

I'll take a look when I can (probably this weekend) and review/merge
through.

Thanks again!

**Comment by memmaa** [comment]
All changes seem sane, and are much appreciated. :-)

**Pull request merged**
